/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package melipona.view.lists;

import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import melipona.model.Cargo;
import service.CargoService;

/**
 *
 * @author uilto
 */
public class listCargo extends javax.swing.JDialog {

    /**
     * Creates new form listCargo
     */
    public listCargo(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        preencherLista(service.AllCargos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleCargos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CargosTable = new javax.swing.JTable();
        BntBack = new javax.swing.JButton();
        BntImport1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        titleCargos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleCargos.setForeground(new java.awt.Color(0, 0, 0));
        titleCargos.setText("Cargos:");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        CargosTable.setBackground(new java.awt.Color(255, 255, 255));
        CargosTable.setForeground(new java.awt.Color(0, 0, 0));
        CargosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Cargo", "Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CargosTable);

        BntBack.setBackground(new java.awt.Color(255, 255, 255));
        BntBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BntBack.setForeground(new java.awt.Color(0, 0, 0));
        BntBack.setText("< Voltar");
        BntBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntBackActionPerformed(evt);
            }
        });

        BntImport1.setBackground(new java.awt.Color(255, 255, 255));
        BntImport1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BntImport1.setForeground(new java.awt.Color(0, 0, 0));
        BntImport1.setText("Importe");
        BntImport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntImport1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(titleCargos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BntBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BntImport1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleCargos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntBack)
                    .addComponent(BntImport1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BntImport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntImport1ActionPerformed
        // TODO add your handling code here:
        if(CargosTable.getSelectedRow() > -1){
            int IdCargo = Integer.parseInt((String) CargosTable.getValueAt(CargosTable.getSelectedRow(), 0)); 
            setCargoSelecionado(service.getCliente(IdCargo));
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_BntImport1ActionPerformed

    private void BntBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BntBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                listClient dialog = new listClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter(){
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntBack;
    private javax.swing.JButton BntImport1;
    private javax.swing.JTable CargosTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleCargos;
    // End of variables declaration//GEN-END:variables
    CargoService service = new CargoService();
    Cargo CargoSelecionado;

    public Cargo getCargoSelecionado() {
        return CargoSelecionado;
    }

    public void setCargoSelecionado(Cargo CargoSelecionado) {
        this.CargoSelecionado = CargoSelecionado;
    }
    
    private void preencherLista(List<Cargo> Cargos){
        String columns[] = {"ID","nome", "CPF"};
        String dados[][] = new String[Cargos.size()][columns.length];
        int i=0;
        
        for (Cargo cargo : Cargos) {
            dados[i] = new String[]{
                String.valueOf(cargo.getId()),
                cargo.getNome(),
                NumberFormat.getCurrencyInstance().format(cargo.getSalario())
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(dados,columns);
        CargosTable.setModel(model);
        
    }
}
