/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package melipona.view.ViwsCad;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import melipona.model.bancoDdados.Estoque;
import melipona.model.Produto;
import melipona.view.EstoqueView;

/**
 *
 * @author uilto
 */
public class CadProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadProduto
     */
    public CadProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        lblQuant = new javax.swing.JLabel();
        txtCusto = new javax.swing.JTextField();
        lblCusto = new javax.swing.JLabel();
        lblValid = new javax.swing.JLabel();
        txtValid = new javax.swing.JFormattedTextField();
        bntCancel = new javax.swing.JButton();
        bntSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setText("Cadastro de Produto");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome:");

        txtNome.setBackground(new java.awt.Color(255, 255, 255));

        txtPreco.setBackground(new java.awt.Color(255, 255, 255));

        lblPreco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(0, 0, 0));
        lblPreco.setText("Preço");

        txtQuant.setBackground(new java.awt.Color(255, 255, 255));

        lblQuant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuant.setForeground(new java.awt.Color(0, 0, 0));
        lblQuant.setText("Quantidade:");

        txtCusto.setBackground(new java.awt.Color(255, 255, 255));

        lblCusto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCusto.setForeground(new java.awt.Color(0, 0, 0));
        lblCusto.setText("Custo Produto:");

        lblValid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValid.setForeground(new java.awt.Color(0, 0, 0));
        lblValid.setText("Validade:");

        txtValid.setBackground(new java.awt.Color(255, 255, 255));
        txtValid.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtValid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bntCancel.setBackground(new java.awt.Color(255, 255, 255));
        bntCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bntCancel.setForeground(new java.awt.Color(0, 0, 0));
        bntCancel.setText("Cancelar");
        bntCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelActionPerformed(evt);
            }
        });

        bntSave.setBackground(new java.awt.Color(0, 0, 0));
        bntSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntSave.setForeground(new java.awt.Color(255, 255, 255));
        bntSave.setText("Salvar");
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(txtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntCancel)
                        .addGap(29, 29, 29)
                        .addComponent(bntSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuant)
                                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCusto))
                                .addGap(68, 68, 68)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPreco)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValid)
                                    .addComponent(txtValid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txtTitulo)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQuant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCusto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblValid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCancel)
                    .addComponent(bntSave))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelActionPerformed
        // TODO add your handling code here:
        if(edit == true){
            EstoqueView ESTOQUE = new EstoqueView();
            ESTOQUE.setVisible(true);
            dispose();
        }
        dispose();
    }//GEN-LAST:event_bntCancelActionPerformed

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
        // TODO add your handling code here:
        if(edit == true){
            editar();
            EstoqueView ESTOQUE = new EstoqueView();
            ESTOQUE.setVisible(true);
            dispose();
        }else{
            cadastrar();
        }
    }//GEN-LAST:event_bntSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancel;
    private javax.swing.JButton bntSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblValid;
    private javax.swing.JTextField txtCusto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JFormattedTextField txtValid;
    // End of variables declaration//GEN-END:variables
    
    public boolean edit = false;
    Produto produtoEdit;

    public boolean isEdit() {
        return edit;
    }

    public void setEdit(boolean edit) {
        this.edit = edit;
    }

    public Produto getProdutoEdit() {
        return produtoEdit;
    }

    public void setProdutoEdit(Produto produtoEdit) {
        this.produtoEdit = produtoEdit;
    }
    
    
    
    private boolean isEmpty(){
        if(txtNome.getText().isEmpty() == false &&
                txtPreco.getText().isEmpty() == false &&
                txtQuant.getText().isEmpty() == false &&
                txtCusto.getText().isEmpty() == false
                ){
            return false;
        }else{
            JOptionPane.showMessageDialog(null, "Preencha Todos os campos obrigatórios");
            return true;
        }
    }
    
    private LocalDate convertStrintToData(String data){
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(data,formatter);
            return date;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Campo de data ou validade invalido");
            return null;
        }
    }
    
    private int convertStringToInt(String number){
        try {
            return Integer.parseInt(number);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Informe um valor valido");
            return 0;
        }
    }
    
    private double convertStringToDouble(String preco){
        try {
            preco = preco.replaceAll(",", ".");
            return Double.parseDouble(preco);
        } catch (Exception e) {
            return 0;
        }
    }
    
    public void setDataEdit(Produto produto){
        txtTitulo.setText("Editar Cadastro");
        setEdit(true);
        produtoEdit = produto;
        txtNome.setText(produtoEdit.getNome());
        txtCusto.setText(toString().valueOf(produtoEdit.getCusto()));
        txtPreco.setText(toString().valueOf(produtoEdit.getPreço()));
        txtQuant.setText(toString().valueOf(produtoEdit.getQuantEstoque()));
        if(produtoEdit.getDatavalid() != null){
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            txtValid.setText(produtoEdit.getDatavalid().format(formatter));
        }
   }
    
    public void cadastrar(){
        int quant = convertStringToInt(txtQuant.getText());
        double preco = convertStringToDouble(txtPreco.getText());
        double custo = convertStringToDouble(txtCusto.getText());
        
        if(txtCusto.getText().replaceAll("/", "").isEmpty() == true){
            if(isEmpty() == false &&
                    quant > 0 &&
                    preco > 0 && 
                    custo > 0){
                Produto produto = new Produto(
                        Estoque.estoque.size(),
                        txtNome.getText(),
                        preco,
                        quant,
                        custo
                );
                Estoque.getEstoque().add(produto);
                JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso");
            }
        }else{
            LocalDate data = convertStrintToData(txtValid.getText());
        
            if(isEmpty() == false &&
                    data != null &&
                    quant > 0 &&
                    preco > 0 &&
                    custo > 0){
                Produto produto = new Produto(
                        Estoque.estoque.size(),
                        txtNome.getText(),
                        preco,
                        quant,
                        data,
                        custo
                );
                Estoque.getEstoque().add(produto);
                JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso");
            }
        }
    }
    
    public void editar(){
        int quant = convertStringToInt(txtQuant.getText());
        double preco = convertStringToDouble(txtPreco.getText());
        double custo = convertStringToDouble(txtCusto.getText());
        
        if(txtCusto.getText().replaceAll("/", "").isEmpty() == true){
            if(isEmpty() == false &&
                    quant > 0 &&
                    preco > 0 && 
                    custo > 0){
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setNome(txtNome.getText());
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setPreço(preco);
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setQuantEstoque(quant);
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setCusto(custo);
                
                JOptionPane.showMessageDialog(null, "Alteração feita com sucesso");
            }
        }else{
            LocalDate data = convertStrintToData(txtValid.getText());
        
            if(isEmpty() == false &&
                    data != null &&
                    quant > 0 &&
                    preco > 0 &&
                    custo > 0){
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setNome(txtNome.getText());
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setPreço(preco);
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setQuantEstoque(quant);
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setDatavalid(data);
                Estoque.getEstoque().get(produtoEdit.getIdProduto()).setCusto(custo);
                
                JOptionPane.showMessageDialog(null, "Alteração feita com sucesso");
            }
        }
    }
}
